/** Declaration file generated by dts-gen */

export function and(...args: any[]): any;

export function check(r: any): any;

export function conform(r: any): any;

export function explain(r: any): any;

export function flex(r: any): any;

export function getMessage(r: any, e: any): any;

export function getMessages(): any;

export function getPred(r: any): any;

export function getSpread(r: any): any;

export function inspect(r: any): any;

export function isFlex(r: any): any;

export function isOpt(r: any): any;

export function isValid(r: any): any;

export function key(r: any): any;

export function nilable(r: any): any;

export function nspector(r: any): any;

export function opt(r: any): any;

export function or(...args: any[]): any;

export function select(e: any, n: any): any;

export function setMessages(r: any): void;

export function spread(r: any, e: any): any;

export function unflex(r: any, e: any, n: any): any;

export function validatePred(r: any, e: any, n: any, t: any): any;

